-- ══════════════════════════════════════════════
--  POKEWEB — Esquema PostgreSQL (Supabase)
--  Ejecutar en: Supabase → SQL Editor → Run
-- ══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS types (
  id       SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_en  VARCHAR(20) NOT NULL UNIQUE,
  name_es  VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS pokemon (
  id            SMALLINT PRIMARY KEY,
  name          VARCHAR(60) NOT NULL UNIQUE,
  name_es       VARCHAR(60) NOT NULL,
  sprite_url    TEXT,
  hp            SMALLINT NOT NULL DEFAULT 0,
  attack        SMALLINT NOT NULL DEFAULT 0,
  defense       SMALLINT NOT NULL DEFAULT 0,
  sp_attack     SMALLINT NOT NULL DEFAULT 0,
  sp_defense    SMALLINT NOT NULL DEFAULT 0,
  speed         SMALLINT NOT NULL DEFAULT 0,
  is_legendary  BOOLEAN NOT NULL DEFAULT FALSE,
  evo_family_id SMALLINT
);

CREATE TABLE IF NOT EXISTS pokemon_types (
  pokemon_id SMALLINT NOT NULL REFERENCES pokemon(id) ON DELETE CASCADE,
  type_id    SMALLINT NOT NULL REFERENCES types(id),
  slot       SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (pokemon_id, slot)
);

CREATE TABLE IF NOT EXISTS moves (
  id         SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(60) NOT NULL UNIQUE,
  name_es    VARCHAR(60) NOT NULL,
  type_id    SMALLINT NOT NULL REFERENCES types(id),
  category   VARCHAR(20) NOT NULL CHECK (category IN ('physical', 'special', 'status')),
  power      SMALLINT,
  accuracy   SMALLINT,
  pp         SMALLINT
);

CREATE TABLE IF NOT EXISTS pokemon_moves (
  pokemon_id   SMALLINT NOT NULL REFERENCES pokemon(id) ON DELETE CASCADE,
  move_id      SMALLINT NOT NULL REFERENCES moves(id),
  learn_method VARCHAR(20) NOT NULL DEFAULT 'level-up'
    CHECK (learn_method IN ('level-up', 'machine', 'egg', 'tutor')),
  level        SMALLINT,
  PRIMARY KEY (pokemon_id, move_id)
);

CREATE TABLE IF NOT EXISTS type_effectiveness (
  attack_type_id  SMALLINT NOT NULL REFERENCES types(id),
  defend_type_id  SMALLINT NOT NULL REFERENCES types(id),
  multiplier      SMALLINT NOT NULL DEFAULT 100,
  PRIMARY KEY (attack_type_id, defend_type_id)
);

CREATE TABLE IF NOT EXISTS games (
  id     SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug   VARCHAR(40) NOT NULL UNIQUE,
  name   VARCHAR(60) NOT NULL,
  region VARCHAR(30) NOT NULL DEFAULT '',
  gen    SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS trainers (
  id              SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug            VARCHAR(80) NOT NULL,
  name            VARCHAR(60) NOT NULL,
  name_es         VARCHAR(60) NOT NULL,
  trainer_class   VARCHAR(20) NOT NULL,
  game_id         SMALLINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  gym_order       SMALLINT,
  badge_name      VARCHAR(40),
  specialty       VARCHAR(40),
  location        VARCHAR(60),
  sprite_url      TEXT,
  team_by_starter JSONB,
  UNIQUE (game_id, slug)
);

CREATE TABLE IF NOT EXISTS trainer_pokemon (
  id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id  SMALLINT NOT NULL REFERENCES trainers(id) ON DELETE CASCADE,
  pokemon_id  SMALLINT NOT NULL REFERENCES pokemon(id),
  level       SMALLINT NOT NULL DEFAULT 50,
  slot        SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS trainer_pokemon_moves (
  trainer_pokemon_id SMALLINT NOT NULL REFERENCES trainer_pokemon(id) ON DELETE CASCADE,
  move_id            SMALLINT NOT NULL REFERENCES moves(id),
  slot               SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (trainer_pokemon_id, slot)
);

CREATE TABLE IF NOT EXISTS user_teams (
  id   SERIAL PRIMARY KEY,
  name VARCHAR(60) NOT NULL DEFAULT 'Mi equipo'
);

CREATE TABLE IF NOT EXISTS user_team_pokemon (
  id         SERIAL PRIMARY KEY,
  team_id    INTEGER NOT NULL REFERENCES user_teams(id) ON DELETE CASCADE,
  pokemon_id SMALLINT NOT NULL REFERENCES pokemon(id),
  slot       SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS user_team_pokemon_moves (
  team_pokemon_id INTEGER NOT NULL REFERENCES user_team_pokemon(id) ON DELETE CASCADE,
  move_id         SMALLINT NOT NULL REFERENCES moves(id),
  slot            SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (team_pokemon_id, slot)
);

CREATE INDEX IF NOT EXISTS idx_trainers_game ON trainers(game_id);
CREATE INDEX IF NOT EXISTS idx_trainer_pokemon_trainer ON trainer_pokemon(trainer_id);
CREATE INDEX IF NOT EXISTS idx_pokemon_moves_pokemon ON pokemon_moves(pokemon_id);
