-- ══════════════════════════════════════════════
--  POKEWEB — Esquema PostgreSQL (Supabase)
--  Ejecutar en SQL Editor del proyecto Supabase
-- ══════════════════════════════════════════════

CREATE TYPE move_category AS ENUM ('physical', 'special', 'status');
CREATE TYPE learn_method AS ENUM ('level-up', 'machine', 'egg', 'tutor');

-- ── Tipos ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS types (
  id       SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_en  VARCHAR(20) NOT NULL UNIQUE,
  name_es  VARCHAR(20) NOT NULL
);

-- ── Pokémon ────────────────────────────────────
CREATE TABLE IF NOT EXISTS pokemon (
  id            SMALLINT PRIMARY KEY,
  name          VARCHAR(60) NOT NULL UNIQUE,
  name_es       VARCHAR(60) NOT NULL,
  sprite_url    TEXT,
  hp            SMALLINT NOT NULL DEFAULT 0,
  attack        SMALLINT NOT NULL DEFAULT 0,
  defense       SMALLINT NOT NULL DEFAULT 0,
  sp_attack     SMALLINT NOT NULL DEFAULT 0,
  sp_defense    SMALLINT NOT NULL DEFAULT 0,
  speed         SMALLINT NOT NULL DEFAULT 0,
  is_legendary  BOOLEAN NOT NULL DEFAULT FALSE,
  evo_family_id SMALLINT NULL
);

CREATE TABLE IF NOT EXISTS pokemon_types (
  pokemon_id SMALLINT NOT NULL REFERENCES pokemon(id) ON DELETE CASCADE,
  type_id    SMALLINT NOT NULL REFERENCES types(id),
  slot       SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (pokemon_id, slot)
);

-- ── Movimientos ────────────────────────────────
CREATE TABLE IF NOT EXISTS moves (
  id         SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(60) NOT NULL UNIQUE,
  name_es    VARCHAR(60) NOT NULL,
  type_id    SMALLINT NOT NULL REFERENCES types(id),
  category   move_category NOT NULL,
  power      SMALLINT NULL,
  accuracy   SMALLINT NULL,
  pp         SMALLINT NULL
);

CREATE TABLE IF NOT EXISTS pokemon_moves (
  pokemon_id   SMALLINT NOT NULL REFERENCES pokemon(id) ON DELETE CASCADE,
  move_id      SMALLINT NOT NULL REFERENCES moves(id) ON DELETE CASCADE,
  learn_method learn_method NOT NULL DEFAULT 'level-up',
  level        SMALLINT NULL,
  PRIMARY KEY (pokemon_id, move_id)
);

-- ── Efectividad de tipos ────────────────────────
CREATE TABLE IF NOT EXISTS type_effectiveness (
  attack_type_id  SMALLINT NOT NULL REFERENCES types(id),
  defend_type_id  SMALLINT NOT NULL REFERENCES types(id),
  multiplier      SMALLINT NOT NULL DEFAULT 100,
  PRIMARY KEY (attack_type_id, defend_type_id)
);

-- ── Juegos ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS games (
  id     SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug   VARCHAR(40) NOT NULL UNIQUE,
  name   VARCHAR(60) NOT NULL,
  region VARCHAR(30) NOT NULL,
  gen    SMALLINT NOT NULL
);

-- ── Entrenadores ───────────────────────────────
CREATE TABLE IF NOT EXISTS trainers (
  id              SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug            VARCHAR(80) NOT NULL,
  name            VARCHAR(60) NOT NULL,
  name_es         VARCHAR(60) NOT NULL,
  trainer_class   VARCHAR(20) NOT NULL,
  game_id         SMALLINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  gym_order       SMALLINT NULL,
  badge_name      VARCHAR(40) NULL,
  specialty       VARCHAR(40) NULL,
  location        VARCHAR(60) NULL,
  sprite_url      TEXT NULL,
  team_by_starter JSONB NULL,
  UNIQUE (game_id, slug)
);

CREATE TABLE IF NOT EXISTS trainer_pokemon (
  id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id  SMALLINT NOT NULL REFERENCES trainers(id) ON DELETE CASCADE,
  pokemon_id  SMALLINT NOT NULL REFERENCES pokemon(id),
  level       SMALLINT NOT NULL DEFAULT 50,
  slot        SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS trainer_pokemon_moves (
  trainer_pokemon_id SMALLINT NOT NULL REFERENCES trainer_pokemon(id) ON DELETE CASCADE,
  move_id            SMALLINT NOT NULL REFERENCES moves(id),
  slot               SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (trainer_pokemon_id, slot)
);

-- ── Equipos de usuario ─────────────────────────
CREATE TABLE IF NOT EXISTS user_teams (
  id   SERIAL PRIMARY KEY,
  name VARCHAR(60) NOT NULL DEFAULT 'Mi equipo'
);

CREATE TABLE IF NOT EXISTS user_team_pokemon (
  id         SERIAL PRIMARY KEY,
  team_id    INT NOT NULL REFERENCES user_teams(id) ON DELETE CASCADE,
  pokemon_id SMALLINT NOT NULL REFERENCES pokemon(id),
  slot       SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS user_team_pokemon_moves (
  team_pokemon_id INT NOT NULL REFERENCES user_team_pokemon(id) ON DELETE CASCADE,
  move_id         SMALLINT NOT NULL REFERENCES moves(id),
  slot            SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (team_pokemon_id, slot)
);

CREATE INDEX IF NOT EXISTS idx_trainers_game ON trainers(game_id);
CREATE INDEX IF NOT EXISTS idx_trainer_pokemon_trainer ON trainer_pokemon(trainer_id);
CREATE INDEX IF NOT EXISTS idx_pokemon_moves_pokemon ON pokemon_moves(pokemon_id);
